version: '3.8'

services:
  amnezia-monitor:
    build: .
    container_name: amnezia-traffic-monitor
    restart: always
    ports:
      - "8338:8338"
    volumes:
      - ./backend/servers.json:/app/backend/servers.json
      - ./backend/metrics.db:/app/backend/metrics.db
